name: minpred
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - transdecoder
  - pip
  - pip:
      - biopython>=1.80
      - numpy>=1.23
      - pandas>=1.5
      - platformdirs>=3.0
      - tensorflow>=2.13
